server:
  port: 8000

spring:
  application:
    name: short-link-gateway
  profiles:
    active: dev
  data:
    redis:
      host: redis
      port: 6379
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
