server:
  port: 8002

spring:
  datasource:
    # ShardingSphere Driver
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere Configuration
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 192.168.150.200
      port: 6379
      password: 123456